name: firstWork flow
on: push

jobs:

    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut
              uses: actions/checkout@v6

            - name: welcome message
              run : echo "welcome"

            - name: List Files
              run : ls

            - name: Read Files
              run : cat readme.md
    
