name: firstWork flow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut
              uses: actions/checkout@v4

            - name: welcome message
              run: |
                echo "welcome"
                ls
                cat README.md

            - name : Generate ASCII Artwork
              run: cowsay -f dragon "Run for coverm I am a Dragon" >> dragon.txt


            # - name: List Files
            #   run: ls

            # - name: Read Files
            #   run: cat README.md
    
