name: ASCII workflow
on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: list all the files
              run : ls -ltra

            - name: Execting Shell scripts
              run: ./ascii-script.sh

              
            

